version: '3'

services:
  listener:
    build:
      context: ./demo
      dockerfile: Dockerfile
    volumes:
      - ./demo:/app
      - maven-repo:/root/.m2
    ports:
      - 5000:8080
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    networks:
      - mynet
    depends_on: 
      - redis

  publisher:
    build:
      context: ./demo1
      dockerfile: Dockerfile
    volumes:
      - ./demo1:/app
      - maven-repo:/root/.m2
    ports:
      - 5001:8080
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    networks:
      - mynet
    depends_on: 
      - redis

  redis:
    container_name: 'guide-redis'
    image: 'redis:latest'
    ports:
      - 6379:6379
    networks:
      - mynet

volumes:
  maven-repo:

networks:
  mynet:
